// <auto-generated>
//   This code file has automatically been generated by the "aqua.tool.Validaton" NuGet package (https://www.nuget.org/packages/aqua.tool.Validaton).
//   Copyright (c) Christof Senn. See license.txt in the package root for license information.
// </auto-generated>

#nullable enable
#pragma warning disable

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

[EditorBrowsable(EditorBrowsableState.Never)]
[SuppressMessage(
    "Major Bug",
    "S3903:Types should be defined in named namespaces",
    Justification = "Global extension method with internal visibility.")]
internal static class Check
{
    /// <summary>
    /// Throws an <see cref="ArgumentNullException"/> if <paramref name="value"/> is <see langword="null"/>,
    /// otherwise the <paramref name="value"/> is returned.
    /// </summary>
    /// <exception cref="ArgumentNullException">Thrown if <paramref name="value"/> is <see langword="null"/>.</exception>
    /// <returns>The <paramref name="value"/> unless it's <see langword="null"/>.</returns>
    [DebuggerStepThrough]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static T CheckNotNull<T>([ValidatedNotNull] this T value, string name) => value ?? throw new ArgumentNullException(name);
}

#pragma warning restore
#nullable restore