// <auto-generated>
//   This code file has automatically been generated by the "aqua.tool.Validaton" NuGet package (https://www.nuget.org/packages/aqua.tool.Validation).
//   Copyright (c) Christof Senn. See license.txt in the package root for license information.
// </auto-generated>

#nullable enable
#pragma warning disable

#if !AQUA_TOOL_VALIDATION_DISABLE

using global::System;
using global::System.Collections.Generic;
using ArgumentException = global::System.ArgumentException;
using ArgumentNullException = global::System.ArgumentNullException;
using CallerArgumentExpressionAttribute = global::System.Runtime.CompilerServices.CallerArgumentExpressionAttribute;
using DebuggerNonUserCodeAttribute = global::System.Diagnostics.DebuggerNonUserCodeAttribute;
using DebuggerStepThroughAttribute = global::System.Diagnostics.DebuggerStepThroughAttribute;
using EditorBrowsableAttribute = global::System.ComponentModel.EditorBrowsableAttribute;
using EditorBrowsableState = global::System.ComponentModel.EditorBrowsableState;
using ExcludeFromCodeCoverageAttribute = global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute;
using GeneratedCodeAttribute = global::System.CodeDom.Compiler.GeneratedCodeAttribute;
using ICollection = global::System.Collections.ICollection;
using IEnumerable = global::System.Collections.IEnumerable;
using MethodImplAttribute = global::System.Runtime.CompilerServices.MethodImplAttribute;
using MethodImplOptions = global::System.Runtime.CompilerServices.MethodImplOptions;
using NotNullAttribute = global::System.Diagnostics.CodeAnalysis.NotNullAttribute;
using StackTraceHiddenAttribute = global::System.Diagnostics.StackTraceHiddenAttribute;
using SuppressMessageAttribute = global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute;

[SuppressMessage(
    "Major Bug",
    "S3903:Types should be defined in named namespaces",
    Justification = "Global extension method.")]
[GeneratedCode("aqua.tool.Validation", "")]
[ExcludeFromCodeCoverage]
[EditorBrowsable(EditorBrowsableState.Never)]
[DebuggerNonUserCode]
[DebuggerStepThrough]
[StackTraceHidden]
#if AQUA_TOOL_VALIDATION_USE_EMBEDDED_ATTRIBUTE
[global::Microsoft.CodeAnalysis.EmbeddedAttribute]
#endif // AQUA_TOOL_VALIDATION_USE_EMBEDDED_ATTRIBUTE
#if AQUA_TOOL_VALIDATION_PUBLIC
public
#else
internal
#endif // AQUA_TOOL_VALIDATION_PUBLIC
static class _Check
{
    private const MethodImplOptions AggressiveInlining = (MethodImplOptions)256;

    // NotNull ////////////////////

    /// <summary>
    ///   Throws an <see cref="ArgumentNullException"/> if <paramref name="value"/> is <see langword="null"/>,
    ///   otherwise the <paramref name="value"/> is returned.
    /// </summary>
    /// <exception cref="ArgumentNullException">Thrown if <paramref name="value"/> is <see langword="null"/>.</exception>
    /// <returns>The <paramref name="value"/> unless it's <see langword="null"/>.</returns>
    [MethodImpl(AggressiveInlining)]
    public static T CheckNotNull<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this T? value,
        [CallerArgumentExpression("value")] string? paramName = null)
        where T : struct
        => value ?? throw new ArgumentNullException(paramName);

    /// <summary>
    ///   Throws an <see cref="ArgumentNullException"/> if <paramref name="value"/> is <see langword="null"/>,
    ///   otherwise the <paramref name="value"/> is returned.
    /// </summary>
    /// <exception cref="ArgumentNullException">Thrown if <paramref name="value"/> is <see langword="null"/>.</exception>
    /// <returns>The <paramref name="value"/> unless it's <see langword="null"/>.</returns>
    [MethodImpl(AggressiveInlining)]
    public static T CheckNotNull<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this T? value,
        [CallerArgumentExpression("value")] string? paramName = null)
        where T : class
        => value ?? throw new ArgumentNullException(paramName);

    /// <summary>
    ///   Throws an <see cref="ArgumentNullException"/> if <paramref name="value"/> is <see langword="null"/>.
    /// </summary>
    /// <exception cref="ArgumentNullException">Thrown if <paramref name="value"/> is <see langword="null"/>.</exception>
    [MethodImpl(AggressiveInlining)]
    public static void AssertNotNull<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this T? value,
        [CallerArgumentExpression("value")] string? paramName = null)
        where T : struct
    {
        if (value is null)
        {
            throw new ArgumentNullException(paramName);
        }
    }

    /// <summary>
    ///   Throws an <see cref="ArgumentNullException"/> if <paramref name="value"/> is <see langword="null"/>.
    /// </summary>
    /// <exception cref="ArgumentNullException">Thrown if <paramref name="value"/> is <see langword="null"/>.</exception>
    [MethodImpl(AggressiveInlining)]
    public static void AssertNotNull<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this T? value,
        [CallerArgumentExpression("value")] string? paramName = null)
        where T : class
    {
        if (value is null)
        {
            throw new ArgumentNullException(paramName);
        }
    }

    // NotNullOrEmpty ////////////////////

    /// <summary>
    ///   Throws if <paramref name="collection"/> is either <see langword="null"/> or empty.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="collection"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If <paramref name="collection"/> is empty.</exception>
    /// <returns>The <paramref name="collection"/> unless it's <see langword="null"/> or empty.</returns>
    [MethodImpl(AggressiveInlining)]
    public static TCollection CheckNotNullOrEmpty<TCollection>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this TCollection? collection,
        [CallerArgumentExpression("collection")] string? paramName = null)
        where TCollection : class, IEnumerable
    {
        if (collection is null)
        {
            throw new ArgumentNullException(paramName);
        }

        EnsureNotEmpty(collection, paramName);

        return collection;
    }

    /// <summary>
    ///   Throws if <paramref name="collection"/> is either <see langword="null"/> or empty.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="collection"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If <paramref name="collection"/> is empty.</exception>
    /// <returns>The <paramref name="collection"/> unless it's <see langword="null"/> or empty.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static TCollection CheckNotNullOrEmpty<TCollection>(
        this TCollection? collection,
        [CallerArgumentExpression("collection")] string? paramName = null)
        where TCollection : struct, IEnumerable
    {
        if (!collection.HasValue)
        {
            throw new ArgumentNullException(paramName);
        }

        var value = collection.Value;
        EnsureNotEmpty(value, paramName);
        return value;
    }

    /// <summary>
    ///   Throws if <paramref name="value"/> is either <see langword="null"/> or empty.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="items"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If <paramref name="items"/> is empty.</exception>
    /// <returns>The <paramref name="items"/> unless it's <see langword="null"/>.</returns>
    [MethodImpl(AggressiveInlining)]
    public static string CheckNotNullOrEmpty(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this string? value,
        [CallerArgumentExpression("value")] string? paramName = null)
    {
        if (value is null)
        {
            throw new ArgumentNullException(paramName);
        }

        if (value.Length == 0)
        {
            throw new ArgumentException("String must not be empty.", paramName);
        }

        return value;
    }

    /// <summary>
    ///   Throws if <paramref name="collection"/> is either <see langword="null"/> or empty.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="collection"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If <paramref name="collection"/> is empty.</exception>
    [MethodImpl(AggressiveInlining)]
    public static void AssertNotNullOrEmpty(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this IEnumerable? collection,
        [CallerArgumentExpression("collection")] string? paramName = null)
    {
        if (collection is null)
        {
            throw new ArgumentNullException(paramName);
        }

        EnsureNotEmpty(collection, paramName);
    }

    /// <summary>
    ///   Throws if <paramref name="value"/> is either <see langword="null"/> or empty.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="value"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If <paramref name="value"/> is empty.</exception>
    [MethodImpl(AggressiveInlining)]
    public static void AssertNotNullOrEmpty(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this string? value,
        [CallerArgumentExpression("value")] string? paramName = null)
    {
        if (value is null)
        {
            throw new ArgumentNullException(paramName);
        }

        if (value.Length == 0)
        {
            throw new ArgumentException("String must not be empty.", paramName);
        }
    }

    private static void EnsureNotEmpty(IEnumerable collection, string? paramName)
    {
        if (collection is ICollection c)
        {
            if (c.Count == 0)
            {
                throw new ArgumentException("Collection must not be empty.", paramName);
            }

            return;
        }

        var e = collection.GetEnumerator();
        try
        {
            if (!e.MoveNext())
            {
                throw new ArgumentException("Collection must not be empty.", paramName);
            }
        }
        finally
        {
            (e as IDisposable)?.Dispose();
        }
    }

    // NotNullOrWhiteSpace ////////////////////

    /// <summary>
    ///   Throws if <paramref name="value"/> is either <see langword="null"/> or white space.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="value"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If <paramref name="value"/> is white space.</exception>
    /// <returns>The <paramref name="value"/> unless it's <see langword="null"/> or white space.</returns>
    [MethodImpl(AggressiveInlining)]
    public static string CheckNotNullOrWhiteSpace(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this string? value,
        [CallerArgumentExpression("value")] string? paramName = null)
    {
        if (value is null)
        {
            throw new ArgumentNullException(paramName);
        }

        if (string.IsNullOrWhiteSpace(value))
        {
            throw new ArgumentException("String must not be empty or white space.", paramName);
        }

        return value;
    }

    /// <summary>
    ///   Throws if <paramref name="items"/> is either <see langword="null"/> or white space.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="value"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If <paramref name="value"/> is white space.</exception>
    [MethodImpl(AggressiveInlining)]
    public static void AssertNotNullOrWhiteSpace(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this string? value,
        [CallerArgumentExpression("value")] string? paramName = null)
    {
        if (value is null)
        {
            throw new ArgumentNullException(paramName);
        }

        if (string.IsNullOrWhiteSpace(value))
        {
            throw new ArgumentException("String must not be empty or white space.", paramName);
        }
    }

    // ItemsNotNull ////////////////////

    /// <summary>
    ///   Throws if either <paramref name="collection"/> or any element contained is <see langword="null"/>.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="collection"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If any element in <paramref name="collection"/> is <see langword="null"/>.</exception>
    /// <returns>The <paramref name="collection"/> unless it or any element contained is <see langword="null"/>.</returns>
    [MethodImpl(AggressiveInlining)]
    public static TCollection CheckItemsNotNull<TCollection>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this TCollection? collection,
        [CallerArgumentExpression("collection")] string? paramName = null)
        where TCollection : IEnumerable
    {
        if (collection is null)
        {
            throw new ArgumentNullException(paramName);
        }

        foreach (object? item in collection)
        {
            if (item is null)
            {
                throw new ArgumentException("Collection must not contain any null items.", paramName);
            }
        }

        return collection;
    }

    /// <summary>
    ///   Throws if either <paramref name="collection"/> or any element contained is <see langword="null"/>.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="collection"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If any element in <paramref name="collection"/> is <see langword="null"/>.</exception>
    [MethodImpl(AggressiveInlining)]
    public static void AssertItemsNotNull(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this IEnumerable? collection,
        [CallerArgumentExpression("collection")] string? paramName = null)
    {
        if (collection is null)
        {
            throw new ArgumentNullException(paramName);
        }

        foreach (object? item in collection)
        {
            if (item is null)
            {
                throw new ArgumentException("Collection must not contain any null items.", paramName);
            }
        }
    }

    // ItemsNotNullOrEmpty ////////////////////

    /// <summary>
    ///   Throws if either <paramref name="collection"/> or any string contained is <see langword="null"/> or empty.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="collection"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If any string in <paramref name="collection"/> is <see langword="null"/> or empty.</exception>
    [MethodImpl(AggressiveInlining)]
    public static void AssertItemsNotNullOrEmpty(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this IEnumerable<string?>? collection,
        [CallerArgumentExpression("collection")] string? paramName = null)
    {
        if (collection is null)
        {
            throw new ArgumentNullException(paramName);
        }

        foreach (var item in collection)
        {
            if (string.IsNullOrEmpty(item))
            {
                throw new ArgumentException("Collection must not contain any null or empty strings.", paramName);
            }
        }
    }

    // ItemsNotNullOrWhiteSpace ////////////////////

    /// <summary>
    ///   Throws if either <paramref name="collection"/> or any string contained is <see langword="null"/> or white space.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="collection"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If any string in <paramref name="collection"/> is <see langword="null"/> or white space.</exception>
    [MethodImpl(AggressiveInlining)]
    public static void AssertItemsNotNullOrWhiteSpace(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this IEnumerable<string?>? collection,
        [CallerArgumentExpression("collection")] string? paramName = null)
    {
        if (collection is null)
        {
            throw new ArgumentNullException(paramName);
        }

        foreach (var item in collection)
        {
            if (string.IsNullOrWhiteSpace(item))
            {
                throw new ArgumentException("Collection must not contain any null or white space strings.", paramName);
            }
        }
    }

    // GreaterThan ////////////////////

    [MethodImpl(AggressiveInlining)]
    public static T CheckGreaterThan<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this T? value,
        T other,
        [CallerArgumentExpression("value")] string? paramName = null)
        where T : struct, IComparable<T>
    {
        value.AssertGreaterThan(other, paramName);
        return value!.Value;
    }

    [MethodImpl(AggressiveInlining)]
    public static T CheckGreaterThan<T>(
        this T value,
        T other,
        [CallerArgumentExpression("value")] string? paramName = null)
        where T : struct, IComparable<T>
    {
        value.AssertGreaterThan(other, paramName);
        return value;
    }

    [MethodImpl(AggressiveInlining)]
    public static void AssertGreaterThan<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this T? value,
        T other,
        [CallerArgumentExpression("value")] string? paramName = null)
        where T : struct, IComparable<T>
    {
        value.AssertNotNull(paramName);
        value!.Value.AssertGreaterThan(other, paramName);
    }

    [MethodImpl(AggressiveInlining)]
    public static void AssertGreaterThan<T>(
        this T value,
        T other,
        [CallerArgumentExpression("value")] string? paramName = null)
        where T : struct, IComparable<T>
    {
        if (value.CompareTo(other) <= 0)
        {
            throw new ArgumentOutOfRangeException(paramName, value, $"Value must be greater than {other}.");
        }
    }

    // GreaterThanOrEqual ////////////////////

    [MethodImpl(AggressiveInlining)]
    public static T CheckGreaterThanOrEqual<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this T? value,
        T other,
        [CallerArgumentExpression("value")] string? paramName = null)
        where T : struct, IComparable<T>
    {
        value.AssertGreaterThanOrEqual(other, paramName);
        return value!.Value;
    }

    [MethodImpl(AggressiveInlining)]
    public static T CheckGreaterThanOrEqual<T>(
        this T value,
        T other,
        [CallerArgumentExpression("value")] string? paramName = null)
        where T : struct, IComparable<T>
    {
        value.AssertGreaterThanOrEqual(other, paramName);
        return value;
    }

    [MethodImpl(AggressiveInlining)]
    public static void AssertGreaterThanOrEqual<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this T? value,
        T other,
        [CallerArgumentExpression("value")] string? paramName = null)
        where T : struct, IComparable<T>
    {
        value.AssertNotNull(paramName);
        value!.Value.AssertGreaterThanOrEqual(other, paramName);
    }

    [MethodImpl(AggressiveInlining)]
    public static void AssertGreaterThanOrEqual<T>(
        this T value,
        T other,
        [CallerArgumentExpression("value")] string? paramName = null)
        where T : struct, IComparable<T>
    {
        if (value.CompareTo(other) < 0)
        {
            throw new ArgumentOutOfRangeException(paramName, value, $"Value must be greater than or equal to {other}.");
        }
    }

    // LessThan ////////////////////

    [MethodImpl(AggressiveInlining)]
    public static T CheckLessThan<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this T? value,
        T other,
        [CallerArgumentExpression("value")] string? paramName = null)
        where T : struct, IComparable<T>
    {
        value.AssertLessThan(other, paramName);
        return value!.Value;
    }

    [MethodImpl(AggressiveInlining)]
    public static T CheckLessThan<T>(
        this T value,
        T other,
        [CallerArgumentExpression("value")] string? paramName = null)
        where T : struct, IComparable<T>
    {
        value.AssertLessThan(other, paramName);
        return value;
    }

    [MethodImpl(AggressiveInlining)]
    public static void AssertLessThan<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this T? value,
        T other,
        [CallerArgumentExpression("value")] string? paramName = null)
        where T : struct, IComparable<T>
    {
        value.AssertNotNull(paramName);
        value!.Value.AssertLessThan(other, paramName);
    }

    [MethodImpl(AggressiveInlining)]
    public static void AssertLessThan<T>(
        this T value,
        T other,
        [CallerArgumentExpression("value")] string? paramName = null)
        where T : struct, IComparable<T>
    {
        if (value.CompareTo(other) >= 0)
        {
            throw new ArgumentOutOfRangeException(paramName, value, $"Value must be less than {other}.");
        }
    }

    // LessThanOrEqual ////////////////////

    [MethodImpl(AggressiveInlining)]
    public static T CheckLessThanOrEqual<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this T? value,
        T other,
        [CallerArgumentExpression("value")] string? paramName = null)
        where T : struct, IComparable<T>
    {
        value.AssertLessThanOrEqual(other, paramName);
        return value!.Value;
    }

    [MethodImpl(AggressiveInlining)]
    public static T CheckLessThanOrEqual<T>(
        this T value,
        T other,
        [CallerArgumentExpression("value")] string? paramName = null)
        where T : struct, IComparable<T>
    {
        value.AssertLessThanOrEqual(other, paramName);
        return value;
    }

    [MethodImpl(AggressiveInlining)]
    public static void AssertLessThanOrEqual<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this T? value,
        T other,
        [CallerArgumentExpression("value")] string? paramName = null)
        where T : struct, IComparable<T>
    {
        value.AssertNotNull(paramName);
        value!.Value.AssertLessThanOrEqual(other, paramName);
    }

    [MethodImpl(AggressiveInlining)]
    public static void AssertLessThanOrEqual<T>(
        this T value,
        T other,
        [CallerArgumentExpression("value")] string? paramName = null)
        where T : struct, IComparable<T>
    {
        if (value.CompareTo(other) > 0)
        {
            throw new ArgumentOutOfRangeException(paramName, value, $"Value must be less than or equal to {other}.");
        }
    }
}

#endif // AQUA_TOOL_VALIDATION_DISABLE
