// <auto-generated>
//   This code file has automatically been generated by the "aqua.tool.Validaton" NuGet package (https://www.nuget.org/packages/aqua.tool.Validation).
//   Copyright (c) Christof Senn. See license.txt in the package root for license information.
// </auto-generated>

#nullable enable
#pragma warning disable

#if !AQUA_TOOL_VALIDATION_DISABLE

using global::System.Collections.Generic;
using global::System.Linq;

using ArgumentException = global::System.ArgumentException;
using ArgumentNullException = global::System.ArgumentNullException;

using DebuggerNonUserCodeAttribute = global::System.Diagnostics.DebuggerNonUserCodeAttribute;
using DebuggerStepThroughAttribute = global::System.Diagnostics.DebuggerStepThroughAttribute;
using StackTraceHiddenAttribute = global::System.Diagnostics.StackTraceHiddenAttribute;

using ExcludeFromCodeCoverageAttribute = global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute;
using SuppressMessageAttribute = global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute;
using NotNullAttribute = global::System.Diagnostics.CodeAnalysis.NotNullAttribute;

using GeneratedCodeAttribute = global::System.CodeDom.Compiler.GeneratedCodeAttribute;

using CallerArgumentExpressionAttribute = global::System.Runtime.CompilerServices.CallerArgumentExpressionAttribute;
using MethodImplAttribute = global::System.Runtime.CompilerServices.MethodImplAttribute;
using MethodImplOptions = global::System.Runtime.CompilerServices.MethodImplOptions;

using EditorBrowsableAttribute = global::System.ComponentModel.EditorBrowsableAttribute;
using EditorBrowsableState = global::System.ComponentModel.EditorBrowsableState;

[SuppressMessage(
    "Major Bug",
    "S3903:Types should be defined in named namespaces",
    Justification = "Global extension method.")]
[GeneratedCode("aqua.tool.Validation", "")]
[ExcludeFromCodeCoverage]
[EditorBrowsable(EditorBrowsableState.Never)]
[DebuggerNonUserCode]
[DebuggerStepThrough]
[StackTraceHidden]
#if AQUA_TOOL_VALIDATION_USE_EMBEDDED_ATTRIBUTE
[global::Microsoft.CodeAnalysis.EmbeddedAttribute]
#endif // AQUA_TOOL_VALIDATION_USE_EMBEDDED_ATTRIBUTE
#if AQUA_TOOL_VALIDATION_PUBLIC
public
#else
internal
#endif // AQUA_TOOL_VALIDATION_PUBLIC
static class _Check
{
    private const MethodImplOptions AggressiveInlining = (MethodImplOptions)256;

    /// <summary>
    ///   Throws an <see cref="ArgumentNullException"/> if <paramref name="value"/> is <see langword="null"/>,
    ///   otherwise the <paramref name="value"/> is returned.
    /// </summary>
    /// <exception cref="ArgumentNullException">Thrown if <paramref name="value"/> is <see langword="null"/>.</exception>
    /// <returns>The <paramref name="value"/> unless it's <see langword="null"/>.</returns>
    [MethodImpl(AggressiveInlining)]
    public static T CheckNotNull<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this T? value,
        [CallerArgumentExpression("value")] string? paramName = null)
        where T : struct
        => value ?? throw new ArgumentNullException(paramName);

    /// <summary>
    ///   Throws an <see cref="ArgumentNullException"/> if <paramref name="value"/> is <see langword="null"/>,
    ///   otherwise the <paramref name="value"/> is returned.
    /// </summary>
    /// <exception cref="ArgumentNullException">Thrown if <paramref name="value"/> is <see langword="null"/>.</exception>
    /// <returns>The <paramref name="value"/> unless it's <see langword="null"/>.</returns>
    [MethodImpl(AggressiveInlining)]
    public static T CheckNotNull<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this T? value,
        [CallerArgumentExpression("value")] string? paramName = null)
        where T : class
        => value ?? throw new ArgumentNullException(paramName);

    /// <summary>
    ///   Throws an <see cref="ArgumentNullException"/> if <paramref name="value"/> is <see langword="null"/>.
    /// </summary>
    /// <exception cref="ArgumentNullException">Thrown if <paramref name="value"/> is <see langword="null"/>.</exception>
    [MethodImpl(AggressiveInlining)]
    public static void AssertNotNull<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this T? value,
        [CallerArgumentExpression("value")] string? paramName = null)
        where T : struct
    {
        if (value is null)
        {
            throw new ArgumentNullException(paramName);
        }
    }

    /// <summary>
    ///   Throws an <see cref="ArgumentNullException"/> if <paramref name="value"/> is <see langword="null"/>.
    /// </summary>
    /// <exception cref="ArgumentNullException">Thrown if <paramref name="value"/> is <see langword="null"/>.</exception>
    [MethodImpl(AggressiveInlining)]
    public static void AssertNotNull<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this T? value,
        [CallerArgumentExpression("value")] string? paramName = null)
        where T : class
    {
        if (value is null)
        {
            throw new ArgumentNullException(paramName);
        }
    }

    /// <summary>
    ///   Throws if <paramref name="items"/> is either <see langword="null"/> or empty.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="items"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If <paramref name="items"/> is empty.</exception>
    /// <returns>The <paramref name="items"/> unless it's <see langword="null"/>.</returns>
    [MethodImpl(AggressiveInlining)]
    public static IEnumerable<T> CheckNotNullOrEmpty<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this IEnumerable<T>? items,
        [CallerArgumentExpression("items")] string? paramName = null)
    {
        if (items is null)
        {
            throw new ArgumentNullException(paramName);
        }

        if (!items.Any())
        {
            throw new ArgumentException("Collection must not be empty.", paramName);
        }

        return items;
    }

    /// <summary>
    ///   Throws if <paramref name="items"/> is either <see langword="null"/> or empty.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="items"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If <paramref name="items"/> is empty.</exception>
    /// <returns>The <paramref name="items"/> unless it's <see langword="null"/>.</returns>
    [MethodImpl(AggressiveInlining)]
    public static IReadOnlyCollection<T> CheckNotNullOrEmpty<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this IReadOnlyCollection<T>? items,
        [CallerArgumentExpression("items")] string? paramName = null)
    {
        if (items is null)
        {
            throw new ArgumentNullException(paramName);
        }

        if (!items.Any())
        {
            throw new ArgumentException("Collection must not be empty.", paramName);
        }

        return items;
    }

    /// <summary>
    ///   Throws if <paramref name="items"/> is either <see langword="null"/> or empty.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="items"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If <paramref name="items"/> is empty.</exception>
    /// <returns>The <paramref name="items"/> unless it's <see langword="null"/>.</returns>
    [MethodImpl(AggressiveInlining)]
    public static IReadOnlyList<T> CheckNotNullOrEmpty<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this IReadOnlyList<T>? items,
        [CallerArgumentExpression("items")] string? paramName = null)
    {
        if (items is null)
        {
            throw new ArgumentNullException(paramName);
        }

        if (!items.Any())
        {
            throw new ArgumentException("Collection must not be empty.", paramName);
        }

        return items;
    }

    /// <summary>
    ///   Throws if <paramref name="items"/> is either <see langword="null"/> or empty.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="items"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If <paramref name="items"/> is empty.</exception>
    /// <returns>The <paramref name="items"/> unless it's <see langword="null"/>.</returns>
    [MethodImpl(AggressiveInlining)]
    public static IReadOnlyDictionary<TKey, TValue> CheckNotNullOrEmpty<TKey, TValue>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this IReadOnlyDictionary<TKey, TValue>? dict,
        [CallerArgumentExpression("dict")] string? paramName = null)
    {
        if (dict is null)
        {
            throw new ArgumentNullException(paramName);
        }

        if (!dict.Any())
        {
            throw new ArgumentException("Collection must not be empty.", paramName);
        }

        return dict;
    }

#if NET5_0_OR_GREATER
    /// <summary>
    ///   Throws if <paramref name="items"/> is either <see langword="null"/> or empty.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="items"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If <paramref name="items"/> is empty.</exception>
    /// <returns>The <paramref name="items"/> unless it's <see langword="null"/>.</returns>
    [MethodImpl(AggressiveInlining)]
    public static IReadOnlySet<T> CheckNotNullOrEmpty<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this IReadOnlySet<T>? set,
        [CallerArgumentExpression("set")] string? paramName = null)
    {
        if (set is null)
        {
            throw new ArgumentNullException(paramName);
        }

        if (!set.Any())
        {
            throw new ArgumentException("Collection must not be empty.", paramName);
        }

        return set;
    }
#endif // NET5_0_OR_GREATER

    /// <summary>
    ///   Throws if <paramref name="value"/> is either <see langword="null"/> or empty.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="items"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If <paramref name="items"/> is empty.</exception>
    /// <returns>The <paramref name="items"/> unless it's <see langword="null"/>.</returns>
    [MethodImpl(AggressiveInlining)]
    public static string CheckNotNullOrEmpty(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this string? value,
        [CallerArgumentExpression("value")] string? paramName = null)
    {
        if (value is null)
        {
            throw new ArgumentNullException(paramName);
        }

        if (value.Length == 0)
        {
            throw new ArgumentException("String must not be empty.", paramName);
        }

        return value;
    }

    /// <summary>
    ///   Throws if <paramref name="value"/> is either <see langword="null"/> or white space.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="value"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If <paramref name="value"/> is white space.</exception>
    /// <returns>The <paramref name="value"/> unless it's <see langword="null"/> or white space.</returns>
    [MethodImpl(AggressiveInlining)]
    public static string CheckNotNullOrWhiteSpace(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this string? value,
        [CallerArgumentExpression("value")] string? paramName = null)
    {
        if (value is null)
        {
            throw new ArgumentNullException(paramName);
        }

        if (string.IsNullOrWhiteSpace(value))
        {
            throw new ArgumentException("String must not be empty or white space.", paramName);
        }

        return value;
    }

    /// <summary>
    ///   Throws if <paramref name="items"/> is either <see langword="null"/> or empty.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="items"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If <paramref name="items"/> is empty.</exception>
    [MethodImpl(AggressiveInlining)]
    public static void AssertNotNullOrEmpty<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this IEnumerable<T>? items,
        [CallerArgumentExpression("items")] string? paramName = null)
    {
        if (items is null)
        {
            throw new ArgumentNullException(paramName);
        }

        if (!items.Any())
        {
            throw new ArgumentException($"{(items is string ? "String" : "Collection")} must not be empty.", paramName);
        }
    }

    /// <summary>
    ///   Throws if <paramref name="items"/> is either <see langword="null"/> or white space.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="value"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If <paramref name="value"/> is white space.</exception>
    [MethodImpl(AggressiveInlining)]
    public static void AssertNotNullOrWhiteSpace(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this string? value,
        [CallerArgumentExpression("value")] string? paramName = null)
    {
        if (value is null)
        {
            throw new ArgumentNullException(paramName);
        }

        if (string.IsNullOrWhiteSpace(value))
        {
            throw new ArgumentException("String must not be empty or white space.", paramName);
        }
    }

    /// <summary>
    ///   Throws if either <paramref name="items"/> or any element contained is <see langword="null"/>.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="items"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If any element in <paramref name="items"/> is <see langword="null"/>.</exception>
    /// <returns>The <paramref name="items"/> unless it or any element contained is <see langword="null"/>.</returns>
    [MethodImpl(AggressiveInlining)]
    public static IEnumerable<T> CheckItemsNotNull<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this IEnumerable<T>? items,
        [CallerArgumentExpression("items")] string? paramName = null)
        where T : class
    {
        if (items is null)
        {
            throw new ArgumentNullException(paramName);
        }

        if (items.Any(x => x is null))
        {
            throw new ArgumentException("Collection must not contain any null items.", paramName);
        }

        return items;
    }

    /// <summary>
    ///   Throws if either <paramref name="items"/> or any element contained is <see langword="null"/>.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="items"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If any element in <paramref name="items"/> is <see langword="null"/>.</exception>
    /// <returns>The <paramref name="items"/> unless it or any element contained is <see langword="null"/>.</returns>
    [MethodImpl(AggressiveInlining)]
    public static IReadOnlyCollection<T> CheckItemsNotNull<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this IReadOnlyCollection<T>? items,
        [CallerArgumentExpression("items")] string? paramName = null)
        where T : class
    {
        if (items is null)
        {
            throw new ArgumentNullException(paramName);
        }

        if (items.Any(x => x is null))
        {
            throw new ArgumentException("Collection must not contain any null items.", paramName);
        }

        return items;
    }

    /// <summary>
    ///   Throws if either <paramref name="items"/> or any element contained is <see langword="null"/>.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="items"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If any element in <paramref name="items"/> is <see langword="null"/>.</exception>
    /// <returns>The <paramref name="items"/> unless it or any element contained is <see langword="null"/>.</returns>
    [MethodImpl(AggressiveInlining)]
    public static IReadOnlyList<T> CheckItemsNotNull<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this IReadOnlyList<T>? items,
        [CallerArgumentExpression("items")] string? paramName = null)
        where T : class
    {
        if (items is null)
        {
            throw new ArgumentNullException(paramName);
        }

        if (items.Any(x => x is null))
        {
            throw new ArgumentException("Collection must not contain any null items.", paramName);
        }

        return items;
    }

#if NET5_0_OR_GREATER
    /// <summary>
    ///   Throws if either <paramref name="items"/> or any element contained is <see langword="null"/>.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="items"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If any element in <paramref name="items"/> is <see langword="null"/>.</exception>
    /// <returns>The <paramref name="items"/> unless it or any element contained is <see langword="null"/>.</returns>
    [MethodImpl(AggressiveInlining)]
    public static IReadOnlySet<T> CheckItemsNotNull<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this IReadOnlySet<T>? items,
        [CallerArgumentExpression("items")] string? paramName = null)
        where T : class
    {
        if (items is null)
        {
            throw new ArgumentNullException(paramName);
        }

        if (items.Any(x => x is null))
        {
            throw new ArgumentException("Collection must not contain any null items.", paramName);
        }

        return items;
    }
#endif // NET5_0_OR_GREATER

    /// <summary>
    ///   Throws if either <paramref name="items"/> or any element contained is <see langword="null"/>.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="items"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If any element in <paramref name="items"/> is <see langword="null"/>.</exception>
    [MethodImpl(AggressiveInlining)]
    public static void AssertItemsNotNull<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this IEnumerable<T>? items,
        [CallerArgumentExpression("items")] string? paramName = null)
        where T : class
    {
        if (items is null)
        {
            throw new ArgumentNullException(paramName);
        }

        if (items.Any(x => x is null))
        {
            throw new ArgumentException("Collection must not contain any null items.", paramName);
        }
    }

    /// <summary>
    ///   Throws if either <paramref name="items"/> or any element contained is <see langword="null"/> or empty.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="items"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If any element in <paramref name="items"/> is <see langword="null"/> or empty.</exception>
    [MethodImpl((MethodImplOptions)AggressiveInlining)]
    public static void AssertItemsNotNullOrEmpty(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this IEnumerable<string?>? items,
        [CallerArgumentExpression("items")] string? paramName = null)
    {
        if (items is null)
        {
            throw new ArgumentNullException(paramName);
        }

        if (items.Any(string.IsNullOrEmpty))
        {
            throw new ArgumentException("Collection must not contain any null or empty strings.", paramName);
        }
    }

    /// <summary>
    ///   Throws if either <paramref name="items"/> or any element contained is <see langword="null"/> or white space.
    /// </summary>
    /// <exception cref="ArgumentNullException">If <paramref name="items"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">If any element in <paramref name="items"/> is <see langword="null"/> or white space.</exception>
    [MethodImpl((MethodImplOptions)AggressiveInlining)]
    public static void AssertItemsNotNullOrWhiteSpace(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [NotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this IEnumerable<string?>? items,
        [CallerArgumentExpression("items")] string? paramName = null)
    {
        if (items is null)
        {
            throw new ArgumentNullException(paramName);
        }

        if (items.Any(string.IsNullOrWhiteSpace))
        {
            throw new ArgumentException("Collection must not contain any null or white space strings.", paramName);
        }
    }
}

#endif // AQUA_TOOL_VALIDATION_DISABLE
