// <auto-generated>
//   This code file has automatically been added by the "Nullable" NuGet package (https://www.myget.org/feed/aqua/package/nuget/aqua.tool.nullable).
//   Copyright (c) Christof Senn. All rights reserved. See license.txt in the package root for license information.
// </auto-generated>

#nullable enable
#pragma warning disable

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

[EditorBrowsable(EditorBrowsableState.Never)]
[SuppressMessage(
    "Major Bug",
    "S3903:Types should be defined in named namespaces",
    Justification = "Global extension method with internal visibility.")]
internal static class Check
{
    [DebuggerStepThrough]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static T CheckNotNull<T>([ValidatedNotNull] this T value, string name) => value ?? throw new ArgumentNullException(name);
}

#pragma warning restore
#nullable restore