// <auto-generated>
//   This code file has automatically been added by the "Nullable" NuGet package (https://www.myget.org/feed/aqua/package/nuget/aqua.tool.nullable).
//   Copyright (c) Christof Senn. All rights reserved. See license.txt in the package root for license information.
// </auto-generated>

#if !NULLABLE_ATTRIBUTES_DISABLE
#nullable enable
#pragma warning disable

namespace System.Diagnostics.CodeAnalysis
{
    using System;
    
    [AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
    internal sealed class ValidatedNotNullAttribute : Attribute
    {
    }
}

#pragma warning restore
#nullable restore
#endif // NULLABLE_ATTRIBUTES_DISABLE