// <auto-generated>
//   This code file has automatically been generated by the "aqua.tool.Nullable" NuGet package (aqua.tool.polyfill.Nullable).
//   Copyright (c) Christof Senn. See license.txt in the package root for license information.
// </auto-generated>

#if !NULLABLE_ATTRIBUTES_DISABLE
#nullable enable
#pragma warning disable

namespace System.Diagnostics.CodeAnalysis
{
    using System;
    using System.Diagnostics;
	
    /// <summary>
    /// Indicates to Code Analysis that a method validates a particular parameter.
    /// </summary>
    [AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
#if !NULLABLE_ATTRIBUTES_INCLUDE_IN_CODE_COVERAGE
    [DebuggerNonUserCode]
#endif
    internal sealed class ValidatedNotNullAttribute : Attribute
    {
    }
}

#pragma warning restore
#nullable restore
#endif // NULLABLE_ATTRIBUTES_DISABLE