// <auto-generated>
//   This code file has automatically been generated by the "aqua.tool.Validaton" NuGet package (https://www.nuget.org/packages/aqua.tool.Validaton).
//   Copyright (c) Christof Senn. See license.txt in the package root for license information.
// </auto-generated>

#pragma warning disable

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

[EditorBrowsable(EditorBrowsableState.Never)]
[DebuggerNonUserCode]
[DebuggerStepThrough]
[SuppressMessage(
    "Major Bug",
    "S3903:Types should be defined in named namespaces",
    Justification = "Global extension method with internal visibility.")]
internal static class Check
{
    private const int AggressiveInlining = 256;

    /// <summary>
    /// Throws an <see cref="ArgumentNullException"/> if <paramref name="value"/> is <see langword="null"/>,
    /// otherwise the <paramref name="value"/> is returned.
    /// </summary>
    /// <exception cref="ArgumentNullException">Thrown if <paramref name="value"/> is <see langword="null"/>.</exception>
    /// <returns>The <paramref name="value"/> unless it's <see langword="null"/>.</returns>
    [MethodImpl((MethodImplOptions)AggressiveInlining)]
    public static T CheckNotNull<T>(
#if !NULLABLE_ATTRIBUTES_DISABLE
        [ValidatedNotNull]
#endif // NULLABLE_ATTRIBUTES_DISABLE
        this T value,
        string name)
        => ReferenceEquals(value, null)
        ? throw new ArgumentNullException(name)
        : value;
}

#pragma warning restore