// <auto-generated>
//   This code file has automatically been generated by the "aqua.tool.polyfill.RequiresPreviewFeatures" NuGet package (https://www.nuget.org/packages/aqua.tool.polyfill.RequiresPreviewFeatures).
//   Copyright (c) Christof Senn. See license.txt in the package root for license information.
// </auto-generated>

#if !AQUA_TOOL_POLYFILL_REQUIRESPREVIEWFEATURES_DISABLE
#nullable enable
#pragma warning disable

namespace System.Runtime.Versioning
{
    using System;
    using System.CodeDom.Compiler;

    /// <summary>
    /// Indicates that an API is in preview. This attribute allows call sites to be flagged with a diagnostic that indicates that a preview feature is used. Authors can use this attribute to ship preview features in their assemblies.
    /// </summary>
    [GeneratedCode("aqua.tool.polyfill.RequiresPreviewFeatures", "")]
    [AttributeUsage(AttributeTargets.Assembly | AttributeTargets.Class | AttributeTargets.Constructor | AttributeTargets.Delegate | AttributeTargets.Enum | AttributeTargets.Event | AttributeTargets.Field | AttributeTargets.Interface | AttributeTargets.Method | AttributeTargets.Module | AttributeTargets.Property | AttributeTargets.Struct, Inherited = false)]
#if AQUA_TOOL_POLYFILL_REQUIRESPREVIEWFEATURES_PUBLIC
    public
#else
    internal
#endif // AQUA_TOOL_POLYFILL_REQUIRESPREVIEWFEATURES_PUBLIC
    sealed class RequiresPreviewFeaturesAttribute : Attribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RequiresPreviewFeaturesAttribute"/> class.
        /// </summary>
        public RequiresPreviewFeaturesAttribute()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RequiresPreviewFeaturesAttribute"/> class with the specified message.
        /// </summary>
        /// <param name="message">An optional message associated with this attribute instance.</param>
        public RequiresPreviewFeaturesAttribute(string? message)
        {
             Message = message;
        }

        /// <summary>
        /// Gets the optional message associated with this attribute instance.
        /// </summary>
        public string? Message { get; }

        /// <summary>
        /// Gets or sets the optional URL associated with this attribute instance.
        /// </summary>
        public string? Url { get; set; }
    }
}

#pragma warning restore
#nullable restore
#endif // AQUA_TOOL_POLYFILL_REQUIRESPREVIEWFEATURES_DISABLE