// <auto-generated>
//   This code file has automatically been generated by the "aqua.tool.polyfill.RequiresPreviewFeatures" NuGet package (https://www.nuget.org/packages/aqua.tool.polyfill.RequiresPreviewFeatures).
//   Copyright (c) Christof Senn. See license.txt in the package root for license information.
// </auto-generated>

#nullable enable
#pragma warning disable

namespace System.Runtime.Versioning
{
    using System;
    using System.CodeDom.Compiler;

    /// <summary>
    /// Polyfill type for [System.Runtime.CompilerServices.RequiresPreviewFeatures, System.Runtime].
    /// </summary>
    [GeneratedCode("aqua.tool.polyfill.RequiresPreviewFeatures", "")]
    [AttributeUsage(AttributeTargets.Assembly | AttributeTargets.Class | AttributeTargets.Constructor | AttributeTargets.Delegate | AttributeTargets.Enum | AttributeTargets.Event | AttributeTargets.Field | AttributeTargets.Interface | AttributeTargets.Method | AttributeTargets.Module | AttributeTargets.Property | AttributeTargets.Struct, Inherited = false)]
    internal sealed class RequiresPreviewFeaturesAttribute : Attribute
    {
        public RequiresPreviewFeaturesAttribute ()
        {
        }

        public RequiresPreviewFeaturesAttribute (string? message)
        {
             Message = message;
        }

        /// <summary>
        /// Gets the optional message associated with this attribute instance.
        /// </summary>
        public string? Message { get; }

        /// <summary>
        /// Gets or sets the optional URL associated with this attribute instance.
        /// </summary>
        public string? Url { get; set; }
    }
}

#pragma warning restore
#nullable restore