// <auto-generated>
//   This code file has automatically been generated by the "aqua.tool.polyfill.StackTraceHidden" NuGet package (https://www.nuget.org/packages/aqua.tool.polyfill.StackTraceHidden).
//   Copyright (c) Christof Senn. See license.txt in the package root for license information.
// </auto-generated>

#if !AQUA_TOOL_POLYFILL_STACKTRACEHIDDEN_DISABLE
#nullable enable
#pragma warning disable

namespace System.Diagnostics
{
    using global::System;
    using global::System.CodeDom.Compiler;
    using global::System.Diagnostics;
    using global::System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// Types and Methods attributed with StackTraceHidden will be omitted from the stack trace text shown in StackTrace.ToString() and Exception.StackTrace
    /// </summary>
    [ExcludeFromCodeCoverage]
    [DebuggerNonUserCode]
    [GeneratedCode("aqua.tool.polyfill.StackTraceHidden", "")]
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Constructor | System.AttributeTargets.Method | System.AttributeTargets.Struct, Inherited=false)]
#if AQUA_TOOL_POLYFILL_STACKTRACEHIDDEN_PUBLIC
    public
#else
    internal
#endif // AQUA_TOOL_POLYFILL_STACKTRACEHIDDEN_PUBLIC
    sealed class StackTraceHiddenAttribute : Attribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StackTraceHiddenAttribute"/> class.
        /// </summary>
        public StackTraceHiddenAttribute()
        {
        }
    }
}

#pragma warning restore
#nullable restore
#endif // AQUA_TOOL_POLYFILL_STACKTRACEHIDDEN_DISABLE