// <auto-generated>
//   This code file has automatically been generated by the "aqua.tool.polyfill.IsExternalInit" NuGet package (https://www.nuget.org/packages/aqua.tool.polyfill.IsExternalInit).
//   Copyright (c) Christof Senn. See license.txt in the package root for license information.
// </auto-generated>

#nullable enable
#pragma warning disable

namespace System.Runtime.CompilerServices
{
    /// <summary>
    /// Polyfill type for "Error CS0518 - Predefined type 'System.Runtime.CompilerServices.IsExternalInit' is not defined or imported".
    /// </summary>
    internal sealed class IsExternalInit
    {
    }
}

#pragma warning restore
#nullable restore